name: "Godoc Coverage"
description: "Ensure godoc coverage"
inputs:
  go-version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges."
    required: false
  stable:
    description: "Whether to download only stable versions"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
        stable: ${{ inputs.stable }}
    - run: go install mtoohey.com/godoc-coverage@latest
      shell: sh
    - run: godoc-coverage .
      shell: sh
